<template>
  <div class="mx-auto max-w-4xl space-y-6 pb-16">
    <div class="rounded-3xl bg-gradient-to-br from-slate-900 to-brand-700 p-7 text-white shadow-xl"><p class="text-xs font-bold uppercase tracking-[.2em] text-brand-200">Privasi & data</p><h1 class="mt-2 text-3xl font-bold">Akun Guru</h1><p class="mt-2 text-sm text-white/75">Kelola keamanan, backup, riwayat aktivitas, dan hak atas data Anda.</p></div>

    <div class="grid gap-5 lg:grid-cols-2">
      <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800"><h2 class="font-bold">Keamanan akun</h2><p class="mt-1 text-xs text-slate-500">{{ user?.email }}</p><p class="mt-2 break-all rounded-lg bg-slate-50 p-2 text-[10px] dark:bg-slate-900">UID kolaborasi: {{ user?.uid }}</p><div class="mt-4 rounded-xl p-3 text-xs" :class="user?.emailVerified ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-900/20' : 'bg-amber-50 text-amber-700 dark:bg-amber-900/20'">{{ user?.emailVerified ? 'Email sudah diverifikasi.' : 'Email belum diverifikasi.' }}</div><div class="mt-4 flex flex-wrap gap-2"><button v-if="!user?.emailVerified" @click="verifikasi" class="rounded-xl bg-brand-600 px-4 py-2 text-xs font-semibold text-white">Kirim verifikasi</button><button @click="resetPassword" class="rounded-xl border border-slate-200 px-4 py-2 text-xs font-semibold dark:border-slate-600">Kirim tautan ganti password</button></div></section>

      <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800"><h2 class="font-bold">Backup dan pemulihan</h2><p class="mt-1 text-xs leading-relaxed text-slate-500">Unduh salinan soal, pengaturan, kop, template, dan riwayat ujian dalam format JSON.</p><div class="mt-4 flex flex-wrap gap-2"><button @click="unduhBackup" :disabled="busy" class="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">Unduh semua data</button><label class="cursor-pointer rounded-xl border border-slate-200 px-4 py-2 text-xs font-semibold dark:border-slate-600"><input type="file" accept="application/json,.json" class="hidden" @change="pulihkanBackup" />Pulihkan backup</label></div><p class="mt-3 text-[11px] text-slate-400">Pemulihan menambahkan soal dari backup; data yang ada tidak dihapus.</p></section>

      <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800"><h2 class="font-bold">Retensi data</h2><p class="mt-1 text-xs text-slate-500">Soal di sampah akan ditandai untuk dibersihkan setelah periode ini.</p><div class="mt-4 flex items-center gap-2"><input v-model.number="retentionDays" type="number" min="7" max="365" class="w-24 rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-slate-600" /><span class="text-xs">hari</span><button @click="simpanRetensi" class="ml-auto rounded-xl bg-brand-600 px-4 py-2 text-xs font-semibold text-white">Simpan</button></div></section>

      <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800"><h2 class="font-bold">Aktivitas terbaru</h2><div v-if="aktivitas.length" class="mt-3 max-h-52 space-y-2 overflow-auto"><div v-for="item in aktivitas" :key="item.id" class="rounded-lg bg-slate-50 p-2.5 text-xs dark:bg-slate-900/40"><p class="font-semibold">{{ labelAksi(item.aksi) }}</p><p class="mt-0.5 text-[10px] text-slate-400">{{ formatTanggal(item.createdAt) }}</p></div></div><p v-else class="mt-4 text-xs text-slate-400">Belum ada aktivitas tercatat.</p></section>
    </div>

    <section class="rounded-2xl border border-red-200 bg-red-50 p-5 dark:border-red-900 dark:bg-red-950/20"><h2 class="font-bold text-red-700 dark:text-red-300">Hapus akun dan seluruh data</h2><p class="mt-1 text-xs text-red-600/80 dark:text-red-300/70">Tindakan ini permanen. Unduh backup terlebih dahulu jika masih membutuhkan data.</p><div class="mt-4 grid gap-2 sm:grid-cols-2"><input v-model="deleteEmail" type="email" :placeholder="user?.email || 'Email akun'" class="rounded-xl border border-red-200 bg-white px-3 py-2 text-sm dark:bg-slate-900" /><input v-model="deletePassword" type="password" placeholder="Kata sandi saat ini" class="rounded-xl border border-red-200 bg-white px-3 py-2 text-sm dark:bg-slate-900" /></div><button @click="hapusSemua" :disabled="busy || deleteEmail !== user?.email || !deletePassword" class="mt-3 rounded-xl bg-red-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-40">Hapus akun saya</button></section>
  </div>
</template>

<script setup>
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, query, setDoc, where, writeBatch } from 'firebase/firestore'
import { questionFingerprint, validateBackup } from '../utils/backup.mjs'
definePageMeta({ middleware: 'auth' })
const { db } = useFirebase()
const { user, kirimVerifikasi, kirimResetPassword, autentikasiUlang, hapusAkunAuth } = useAuth()
const { success, error, warning } = useToast()
const { catatAktivitas } = useAuditLog()
const busy = ref(false), aktivitas = ref([]), retentionDays = ref(30), deleteEmail = ref(''), deletePassword = ref('')
const koleksiMilikGuru = ['soal', 'riwayatUjian', 'kopUjian', 'templateUjian', 'auditAktivitas', 'draftGuru', 'analisisUjian', 'ruangKolaborasi']

const verifikasi = async () => { try { await kirimVerifikasi(); success('Email verifikasi telah dikirim.'); } catch (e) { error(`Gagal mengirim verifikasi: ${e.message}`) } }
const resetPassword = async () => { try { await kirimResetPassword(); success('Tautan ganti password telah dikirim ke email Anda.'); } catch (e) { error(`Gagal mengirim tautan: ${e.message}`) } }
const ambilKoleksi = async nama => { const snap = await getDocs(query(collection(db, nama), where('userId', '==', user.value.uid))); return snap.docs.map(d => ({ id: d.id, ...d.data() })) }
const unduhBackup = async () => { busy.value = true; try { const entries = await Promise.all(koleksiMilikGuru.map(async nama => [nama, await ambilKoleksi(nama)])); const pengaturan = await getDoc(doc(db, 'pengaturanGuru', user.value.uid)); const payload = { version: 1, exportedAt: new Date().toISOString(), uid: user.value.uid, pengaturanGuru: pengaturan.exists() ? pengaturan.data() : null, ...Object.fromEntries(entries) }; const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `backup-soalify-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(url); await catatAktivitas('backup_diunduh'); success('Backup berhasil dibuat.'); } catch (e) { error(`Backup gagal: ${e.message}`) } finally { busy.value = false } }
const pulihkanBackup = async event => { const file = event.target.files?.[0]; if (!file) return; busy.value = true; try { const data = validateBackup(JSON.parse(await file.text())); const existing = await ambilKoleksi('soal'); const fingerprints = new Set(existing.map(questionFingerprint)); let restored = 0, skipped = 0; for (const soal of data.soal) { const fingerprint = questionFingerprint(soal); if (fingerprints.has(fingerprint)) { skipped++; continue } const { id, userId, ...isi } = soal; await addDoc(collection(db, 'soal'), { ...isi, userId: user.value.uid, status: isi.status || 'aktif', restoredAt: new Date(), updatedAt: new Date() }); fingerprints.add(fingerprint); restored++; } if (data.pengaturanGuru) await setDoc(doc(db, 'pengaturanGuru', user.value.uid), data.pengaturanGuru, { merge: true }); await catatAktivitas('backup_dipulihkan', { jumlahSoal: restored, dilewati: skipped }); success(`${restored} soal dipulihkan; ${skipped} duplikat dilewati.`); } catch (e) { error(`Pemulihan gagal: ${e.message}`) } finally { busy.value = false; event.target.value = '' } }
const simpanRetensi = async () => { retentionDays.value = Math.min(365, Math.max(7, Number(retentionDays.value) || 30)); await setDoc(doc(db, 'pengaturanGuru', user.value.uid), { privasi: { retentionDays: retentionDays.value } }, { merge: true }); success('Periode retensi disimpan.'); }
const hapusSemua = async () => { if (!confirm('Hapus akun dan seluruh data secara permanen?')) return; busy.value = true; try { await autentikasiUlang(deletePassword.value); for (const nama of koleksiMilikGuru) { const snap = await getDocs(query(collection(db, nama), where('userId', '==', user.value.uid))); for (let i = 0; i < snap.docs.length; i += 400) { const batch = writeBatch(db); snap.docs.slice(i, i + 400).forEach(item => batch.delete(item.ref)); await batch.commit(); } } await deleteDoc(doc(db, 'pengaturanGuru', user.value.uid)); await hapusAkunAuth(); navigateTo('/login'); } catch (e) { error(`Akun belum dapat dihapus: ${e.message}`); } finally { busy.value = false } }
const labelAksi = value => String(value || '').replaceAll('_', ' ').replace(/^./, c => c.toUpperCase())
const formatTanggal = value => { const date = value?.toDate ? value.toDate() : new Date(value); return Number.isNaN(date.getTime()) ? '-' : new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(date) }
onMounted(async () => { const settings = await getDoc(doc(db, 'pengaturanGuru', user.value.uid)); retentionDays.value = settings.data()?.privasi?.retentionDays || 30; aktivitas.value = (await ambilKoleksi('auditAktivitas')).sort((a,b) => (b.createdAt?.seconds || 0) - (a.createdAt?.seconds || 0)).slice(0, 20) })
</script>
