<template>
  <div class="ui-page">
    <div class="rounded-3xl bg-gradient-to-br from-indigo-800 to-brand-600 p-6 text-white shadow-xl sm:p-8"><div class="mb-3 inline-flex rounded-full bg-white/15 px-3 py-1 text-[11px] font-bold">Analisis otomatis pilihan ganda</div><h1 class="text-2xl font-bold sm:text-3xl">Analisis Hasil Ujian</h1><p class="mt-2 max-w-xl text-sm text-white/75">Pilih ujian, impor jawaban A–D siswa, lalu lihat nilai dan kualitas setiap butir PG.</p></div>
    <section class="ui-card ui-card-body"><div class="mb-5 flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-full bg-brand-600 text-sm font-bold text-white">1</span><div><h2 class="ui-section-title">Pilih ujian dan unggah hasil</h2><p class="ui-section-help">Gunakan riwayat ujian yang urutan soalnya sama dengan lembar siswa.</p></div></div><div class="grid gap-4 md:grid-cols-[1fr_auto]"><div><label class="ui-label">Riwayat ujian</label><select v-model="selectedHistoryId" class="ui-input"><option value="">Pilih ujian…</option><option v-for="item in histories" :key="item.id" :value="item.id">{{ item.namaUjian }} · {{ item.mapel }} · Kelas {{ item.kelas }}</option></select><p class="mt-2 text-[11px] text-slate-500">Format: <code>nama,nomor,jawaban</code> dengan jawaban seperti <code>a|c|b|d</code>.</p></div><div class="flex flex-col gap-2 sm:flex-row md:items-end"><button @click="downloadTemplate" class="ui-button-secondary">Unduh template</button><label :class="['ui-button-primary cursor-pointer', !selectedHistory && 'pointer-events-none opacity-50']"><input type="file" accept=".csv,text/csv" class="hidden" @change="importResults" />Impor hasil</label></div></div></section>
    <div v-if="!histories.length" class="ui-card p-8 text-center"><p class="font-semibold">Belum ada riwayat ujian</p><p class="mt-1 text-xs text-slate-500">Cetak sebuah ujian terlebih dahulu agar hasilnya dapat dianalisis.</p><NuxtLink to="/dashboard" class="ui-button-primary mt-4">Buka bank soal</NuxtLink></div>
    <section v-if="selectedHistory" class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div v-for="card in summaryCards" :key="card.label" class="rounded-2xl border bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><p class="text-xs text-slate-500">{{ card.label }}</p><p class="mt-1 text-2xl font-bold">{{ card.value }}</p></div></section>
    <div v-if="selectedHistory && essayCount" class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800 dark:border-amber-900 dark:bg-amber-950/20 dark:text-amber-300"><b>{{ essayCount }} soal esai tidak dihitung otomatis.</b><p class="mt-1 text-xs">Nilai dan analisis di halaman ini hanya berdasarkan {{ questions.length }} soal pilihan ganda. Esai tetap dinilai manual oleh guru.</p></div>
    <section v-if="students.length" class="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><div class="mb-3 flex items-center justify-between"><h2 class="font-bold">Hasil siswa</h2><button @click="saveAnalysis" class="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-semibold text-white">Simpan analisis</button></div><div class="overflow-x-auto"><table class="w-full text-left text-xs"><thead class="border-b text-slate-500"><tr><th class="p-2">Nama</th><th class="p-2">Nomor</th><th class="p-2">Benar</th><th class="p-2">Nilai</th></tr></thead><tbody><tr v-for="student in scoredStudents" :key="student.nomor" class="border-b dark:border-slate-700"><td class="p-2 font-semibold">{{ student.nama }}</td><td class="p-2">{{ student.nomor }}</td><td class="p-2">{{ student.benar }}/{{ answerKeys.length }}</td><td class="p-2 font-bold">{{ student.nilai }}</td></tr></tbody></table></div></section>
    <section v-if="itemAnalysis.length" class="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><h2 class="mb-3 font-bold">Analisis butir soal</h2><div class="grid gap-2"><div v-for="item in itemAnalysis" :key="item.nomor" class="grid items-start gap-2 rounded-xl border p-3 text-xs dark:border-slate-700 sm:grid-cols-[70px_minmax(0,1fr)_150px]"><b class="pt-0.5">Soal {{ item.nomor }}</b><MathText :text="item.pertanyaan" tag="div" class="min-w-0 leading-relaxed text-slate-700 dark:text-slate-200" /><span :class="['whitespace-nowrap pt-0.5 sm:text-right', item.rate < 30 || item.rate > 90 ? 'text-red-600' : 'text-emerald-600']">{{ item.rate }}% benar · {{ item.label }}</span></div></div></section>
  </div>
</template>

<script setup>
import { addDoc, collection, getDocs, limit, query, where } from 'firebase/firestore'
definePageMeta({ middleware: 'auth' })
const { db } = useFirebase(), { user } = useAuth(), { success, error } = useToast(), { catatAktivitas } = useAuditLog()
const histories = ref([]), selectedHistoryId = ref(''), students = ref([])
const selectedHistory = computed(() => histories.value.find(item => item.id === selectedHistoryId.value))
const questions = computed(() => selectedHistory.value?.payload?.pg || selectedHistory.value?.payload?.pakets?.[0]?.pg || [])
const essayCount = computed(() => (selectedHistory.value?.payload?.essay || selectedHistory.value?.payload?.pakets?.[0]?.essay || []).length)
const answerKeys = computed(() => questions.value.map(item => String(item.kunciJawaban || '').toLowerCase()))
const scoredStudents = computed(() => students.value.map(student => { const benar = student.jawaban.filter((answer, index) => answerKeys.value[index] && answer === answerKeys.value[index]).length; return { ...student, benar, nilai: answerKeys.value.length ? Math.round(benar / answerKeys.value.length * 100) : 0 } }))
const average = computed(() => scoredStudents.value.length ? Math.round(scoredStudents.value.reduce((sum, item) => sum + item.nilai, 0) / scoredStudents.value.length) : 0)
const itemAnalysis = computed(() => questions.value.map((question, index) => { const benar = students.value.filter(student => student.jawaban[index] === answerKeys.value[index]).length; const rate = students.value.length ? Math.round(benar / students.value.length * 100) : 0; return { nomor: index + 1, pertanyaan: question.pertanyaan, rate, label: rate < 30 ? 'Sulit' : rate > 70 ? 'Mudah' : 'Sedang' } }))
const summaryCards = computed(() => [{ label: 'Jumlah siswa', value: students.value.length }, { label: 'Rata-rata', value: average.value }, { label: 'Nilai tertinggi', value: Math.max(0, ...scoredStudents.value.map(item => item.nilai)) }, { label: 'Butir perlu ditinjau', value: itemAnalysis.value.filter(item => item.rate < 30 || item.rate > 90).length }])
const parseLine = line => { const [nama = '', nomor = '', jawaban = ''] = line.split(','); return { nama: nama.trim(), nomor: nomor.trim(), jawaban: jawaban.split('|').map(value => value.trim().toLowerCase()) } }
const importResults = async event => { try { if (!selectedHistory.value) throw new Error('Pilih riwayat ujian terlebih dahulu'); const lines = (await event.target.files?.[0]?.text()).split(/\r?\n/).filter(Boolean); students.value = lines.slice(1).map(parseLine).filter(item => item.nama); success(`${students.value.length} hasil siswa berhasil dibaca.`) } catch (e) { error(e.message) } finally { event.target.value = '' } }
const downloadTemplate = () => { const url = URL.createObjectURL(new Blob(['nama,nomor,jawaban\nBudi,01,a|b|c|d'], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'template-hasil-ujian.csv'; link.click(); URL.revokeObjectURL(url) }
const saveAnalysis = async () => { if (!selectedHistory.value || !students.value.length) return; await addDoc(collection(db, 'analisisUjian'), { userId: user.value.uid, riwayatId: selectedHistory.value.id, namaUjian: selectedHistory.value.namaUjian, kelas: selectedHistory.value.kelas, mapel: selectedHistory.value.mapel, siswa: scoredStudents.value, analisisButir: itemAnalysis.value, rataRata: average.value, createdAt: new Date() }); await catatAktivitas('analisis_ujian_disimpan', { riwayatId: selectedHistory.value.id }); success('Analisis berhasil disimpan.') }
onMounted(async () => { if (!user.value) return; const snap = await getDocs(query(collection(db, 'riwayatUjian'), where('userId', '==', user.value.uid), limit(50))); histories.value = snap.docs.map(doc => ({ id: doc.id, ...doc.data() })).sort((a,b) => (b.createdAt?.seconds || 0) - (a.createdAt?.seconds || 0)) })
</script>
