<template>
  <div class="ui-page">
    <div class="rounded-3xl bg-gradient-to-br from-emerald-800 to-teal-600 p-6 text-white shadow-xl sm:p-8"><p class="text-xs font-bold uppercase tracking-[.2em] text-emerald-100">Ruang guru</p><h1 class="mt-2 text-2xl font-bold sm:text-3xl">Kolaborasi Bank Soal</h1><p class="mt-2 max-w-xl text-sm text-white/75">Buat ruang untuk tim Anda atau gabung menggunakan kode dari guru lain.</p></div>
    <section class="ui-card ui-card-body"><div class="mb-4"><h2 class="ui-section-title">Buat ruang baru</h2><p class="ui-section-help">Nama dan izin dapat disesuaikan dengan kebutuhan tim guru.</p></div><div class="grid gap-3 sm:grid-cols-2"><div><label class="ui-label">Nama ruang</label><input v-model.trim="form.nama" placeholder="Contoh: Tim Matematika Kelas 4" class="ui-input" /></div><div><label class="ui-label">Hak akses anggota</label><select v-model="form.izin" class="ui-input"><option value="lihat">Melihat dan menyalin</option><option value="edit">Melihat dan mengedit</option></select></div><div class="sm:col-span-2"><label class="ui-label">UID anggota <span class="font-normal text-slate-400">(opsional)</span></label><textarea v-model.trim="form.memberInput" rows="2" class="ui-input" placeholder="Pisahkan beberapa UID dengan koma. UID tersedia di halaman Akun." /></div></div><button @click="createRoom" :disabled="!form.nama" class="ui-button-primary mt-4 bg-emerald-600 hover:bg-emerald-700">Buat ruang</button></section>
    <section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><article v-for="room in rooms" :key="room.id" class="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><div class="flex justify-between gap-2"><h2 class="font-bold">{{ room.nama }}</h2><span class="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">{{ room.izin }}</span></div><p class="mt-2 text-xs text-slate-500">{{ room.questions?.length || 0 }} soal · {{ room.memberIds?.length || 0 }} anggota</p><div v-if="room.questions?.length" class="mt-3 max-h-36 space-y-1 overflow-auto"><p v-for="(question, index) in room.questions" :key="`${room.id}-${index}`" class="truncate rounded-lg bg-slate-50 p-2 text-[11px] dark:bg-slate-900">{{ index + 1 }}. {{ question.pertanyaan }}</p></div><p class="mt-3 break-all rounded-lg bg-slate-50 p-2 text-[10px] dark:bg-slate-900">Kode: {{ room.id }}</p><div class="mt-3 flex flex-wrap gap-2"><button @click="copyCode(room.id)" class="rounded-lg border px-3 py-2 text-xs font-semibold">Salin kode</button><button v-if="room.editorIds?.includes(user?.uid)" @click="selectedRoomId = room.id" class="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700">Tambah soal</button><button v-if="room.ownerId === user?.uid" @click="deleteRoom(room)" class="rounded-lg px-3 py-2 text-xs font-semibold text-red-600">Hapus</button></div></article></section>
    <section v-if="selectedRoomId" class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 dark:border-emerald-900 dark:bg-emerald-950/20"><div class="flex items-center justify-between"><h2 class="font-bold">Pilih soal untuk ruang</h2><button @click="selectedRoomId = ''" class="text-xs">Tutup</button></div><div class="mt-3 max-h-64 space-y-2 overflow-auto"><label v-for="question in ownQuestions" :key="question.id" class="flex gap-2 rounded-xl bg-white p-3 text-xs dark:bg-slate-800"><input v-model="selectedQuestionIds" type="checkbox" :value="question.id" /><span>{{ question.mapel }} · Kelas {{ question.kelas }} — {{ question.pertanyaan }}</span></label></div><button @click="addQuestions" :disabled="!selectedQuestionIds.length" class="mt-3 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-40">Tambahkan {{ selectedQuestionIds.length }} soal</button></section>
    <section class="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><h2 class="font-bold">Gabung dengan kode</h2><div class="mt-3 flex gap-2"><input v-model.trim="joinCode" placeholder="Masukkan kode ruang" class="min-w-0 flex-1 rounded-xl border bg-transparent px-3 py-2 text-sm dark:border-slate-700" /><button @click="joinRoom" class="rounded-xl bg-slate-900 px-4 py-2 text-xs font-semibold text-white dark:bg-slate-700">Gabung</button></div><p class="mt-2 text-[11px] text-slate-500">Pemilik ruang tetap mengendalikan daftar anggota dan hak edit.</p></section>
  </div>
</template>

<script setup>
import { addDoc, arrayUnion, collection, deleteDoc, doc, getDoc, getDocs, limit, query, updateDoc, where } from 'firebase/firestore'
definePageMeta({ middleware: 'auth' })
const { db } = useFirebase(), { user } = useAuth(), { success, error } = useToast(), { catatAktivitas } = useAuditLog()
const rooms = ref([]), ownQuestions = ref([]), selectedRoomId = ref(''), selectedQuestionIds = ref([]), joinCode = ref(''), form = reactive({ nama: '', izin: 'lihat', memberInput: '' })
const loadRooms = async () => { if (!user.value) return; const snap = await getDocs(query(collection(db, 'ruangKolaborasi'), where('memberIds', 'array-contains', user.value.uid), limit(30))); rooms.value = snap.docs.map(item => ({ id: item.id, ...item.data() })) }
const createRoom = async () => { const extra = form.memberInput.split(',').map(value => value.trim()).filter(Boolean); const memberIds = [...new Set([user.value.uid, ...extra])]; const created = await addDoc(collection(db, 'ruangKolaborasi'), { ownerId: user.value.uid, userId: user.value.uid, nama: form.nama, izin: form.izin, memberIds, editorIds: form.izin === 'edit' ? memberIds : [user.value.uid], questionIds: [], createdAt: new Date(), updatedAt: new Date() }); await catatAktivitas('ruang_kolaborasi_dibuat', { ruangId: created.id }); form.nama = ''; form.memberInput = ''; await loadRooms(); success('Ruang kolaborasi dibuat.') }
const joinRoom = async () => { try { const target = await getDoc(doc(db, 'ruangKolaborasi', joinCode.value)); if (!target.exists()) throw new Error('Kode ruang tidak ditemukan'); await updateDoc(target.ref, { memberIds: arrayUnion(user.value.uid), updatedAt: new Date() }); joinCode.value = ''; await loadRooms(); success('Berhasil bergabung.') } catch (e) { error(e.message || 'Tidak dapat bergabung. Minta pemilik menambahkan UID Anda.') } }
const copyCode = async code => { await navigator.clipboard.writeText(code); success('Kode ruang disalin.') }
const addQuestions = async () => { const room = rooms.value.find(item => item.id === selectedRoomId.value); if (!room) return; const existing = room.questions || []; const additions = ownQuestions.value.filter(item => selectedQuestionIds.value.includes(item.id)).map(({ id, userId, ...item }) => ({ sourceId: id, sourceOwnerId: user.value.uid, ...item })); const merged = [...existing, ...additions.filter(item => !existing.some(saved => saved.sourceId === item.sourceId))].slice(0, 200); await updateDoc(doc(db, 'ruangKolaborasi', room.id), { questions: merged, questionIds: merged.map(item => item.sourceId), updatedAt: new Date() }); selectedQuestionIds.value = []; selectedRoomId.value = ''; await loadRooms(); success('Soal ditambahkan ke ruang bersama.') }
const deleteRoom = async room => { if (!confirm(`Hapus ruang “${room.nama}”?`)) return; await deleteDoc(doc(db, 'ruangKolaborasi', room.id)); await loadRooms() }
onMounted(async () => { await loadRooms(); if (!user.value) return; const snap = await getDocs(query(collection(db, 'soal'), where('userId', '==', user.value.uid), where('status', '==', 'aktif'), limit(100))); ownQuestions.value = snap.docs.map(item => ({ id: item.id, ...item.data() })) })
</script>
