<template>
  <div class="ui-page">
    <div class="rounded-3xl bg-gradient-to-br from-emerald-800 to-teal-600 p-6 text-white shadow-xl sm:p-8"><p class="text-xs font-bold uppercase tracking-[.2em] text-emerald-100">Ruang guru</p><h1 class="mt-2 text-2xl font-bold sm:text-3xl">Kolaborasi Bank Soal</h1><p class="mt-2 max-w-xl text-sm text-white/75">Buat ruang untuk tim Anda atau gabung menggunakan kode dari guru lain.</p></div>
    <div class="grid gap-4 lg:grid-cols-2"><section class="ui-card ui-card-body"><div class="mb-4 flex items-start gap-3"><span class="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-emerald-600 text-sm font-bold text-white">1</span><div><h2 class="ui-section-title">Buat ruang baru</h2><p class="ui-section-help">Buat ruang, tambahkan soal, lalu kirim kodenya kepada guru lain.</p></div></div><label class="ui-label">Nama ruang</label><input v-model.trim="form.nama" placeholder="Contoh: Tim Matematika Kelas 4" class="ui-input" /><button @click="createRoom" :disabled="!form.nama" class="ui-button-primary mt-4 bg-emerald-600 hover:bg-emerald-700">Buat ruang</button></section><section class="ui-card ui-card-body"><div class="mb-4 flex items-start gap-3"><span class="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-800 text-sm font-bold text-white dark:bg-slate-600">2</span><div><h2 class="ui-section-title">Gabung ke ruang</h2><p class="ui-section-help">Tempel kode yang dikirim oleh pemilik ruang.</p></div></div><label class="ui-label">Kode ruang</label><div class="flex gap-2"><input v-model.trim="joinCode" placeholder="Contoh: AbC123…" class="ui-input min-w-0" /><button @click="joinRoom" :disabled="!joinCode" class="ui-button-primary shrink-0 bg-slate-900 dark:bg-slate-700">Gabung</button></div></section></div>
    <div v-if="rooms.length"><h2 class="ui-section-title">Ruang yang Anda ikuti</h2><p class="ui-section-help">Pemilik menambahkan soal, anggota dapat melihat dan menyalinnya.</p></div><section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><article v-for="room in rooms" :key="room.id" class="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><div class="flex justify-between gap-2"><h2 class="font-bold">{{ room.nama }}</h2><span class="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">{{ room.ownerId === user?.uid ? 'Pemilik' : 'Anggota' }}</span></div><p class="mt-2 text-xs text-slate-500">{{ room.questions?.length || 0 }} soal · {{ room.memberIds?.length || 0 }} anggota</p><div v-if="room.questions?.length" class="mt-3 max-h-44 space-y-1 overflow-auto"><div v-for="(question, index) in room.questions" :key="`${room.id}-${index}`" class="rounded-lg bg-slate-50 p-2 text-[11px] dark:bg-slate-900"><b>{{ index + 1 }}.</b> <MathText :text="question.pertanyaan" /></div></div><p v-else class="mt-3 rounded-lg border border-dashed p-3 text-center text-[11px] text-slate-400">Belum ada soal di ruang ini.</p><p class="mt-3 break-all rounded-lg bg-slate-50 p-2 text-[10px] dark:bg-slate-900">Kode: {{ room.id }}</p><div class="mt-3 flex flex-wrap gap-2"><button @click="copyCode(room.id)" class="rounded-lg border px-3 py-2 text-xs font-semibold">Bagikan kode</button><button v-if="room.ownerId === user?.uid" @click="selectedRoomId = room.id" class="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700">Tambah soal</button><button v-if="room.ownerId !== user?.uid && room.questions?.length" @click="copyRoomQuestions(room)" :disabled="!destinationKey || copyingRoomId === room.id" class="rounded-lg bg-brand-50 px-3 py-2 text-xs font-semibold text-brand-700 disabled:opacity-40">{{ copyingRoomId === room.id ? 'Menyalin…' : 'Salin ke bank saya' }}</button><button v-if="room.ownerId === user?.uid" @click="deleteRoom(room)" class="rounded-lg px-3 py-2 text-xs font-semibold text-red-600">Hapus</button></div></article></section>
    <section v-if="rooms.some(room => room.ownerId !== user?.uid)" class="ui-card ui-card-body"><h2 class="ui-section-title">Tujuan salinan soal</h2><p class="ui-section-help">Pilih bank tujuan sebelum menekan “Salin ke bank saya”.</p><select v-model="destinationKey" class="ui-input mt-3"><option value="">Pilih kelas dan mata pelajaran…</option><option v-for="item in destinationOptions" :key="item.key" :value="item.key">{{ item.label }}</option></select><p v-if="!destinationOptions.length" class="mt-2 text-xs text-amber-600">Buat minimal satu soal di bank pribadi terlebih dahulu agar tujuan dapat dikenali.</p></section>
    <section v-if="selectedRoomId" class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 dark:border-emerald-900 dark:bg-emerald-950/20"><div class="flex items-center justify-between"><h2 class="font-bold">Pilih soal untuk ruang</h2><button @click="selectedRoomId = ''" class="text-xs">Tutup</button></div><div class="mt-3 max-h-64 space-y-2 overflow-auto"><label v-for="question in ownQuestions" :key="question.id" class="flex gap-2 rounded-xl bg-white p-3 text-xs dark:bg-slate-800"><input v-model="selectedQuestionIds" type="checkbox" :value="question.id" /><span>{{ question.mapel }} · Kelas {{ question.kelas }} — {{ question.pertanyaan }}</span></label></div><button @click="addQuestions" :disabled="!selectedQuestionIds.length" class="mt-3 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-40">Tambahkan {{ selectedQuestionIds.length }} soal</button></section>
  </div>
</template>

<script setup>
import { addDoc, arrayUnion, collection, collectionGroup, deleteDoc, doc, getDoc, getDocs, limit, query, updateDoc, where } from 'firebase/firestore'
definePageMeta({ middleware: 'auth' })
const { db } = useFirebase(), { user } = useAuth(), { success, error } = useToast(), { catatAktivitas } = useAuditLog()
const { bankIdFor, questionsRefFor, ensureBank } = useQuestionBanks()
const rooms = ref([]), ownQuestions = ref([]), selectedRoomId = ref(''), selectedQuestionIds = ref([]), joinCode = ref(''), destinationKey = ref(''), copyingRoomId = ref(''), form = reactive({ nama: '' })
const destinationOptions = computed(() => [...new Map(ownQuestions.value.map(item => { const key = `${item.assignmentId || 'legacy'}|${item.kelas}|${item.mapel}`; return [key, { key, assignmentId: item.assignmentId || 'legacy', kelas: item.kelas, mapel: item.mapel, jenjang: item.jenjang || 'SD', namaSekolah: item.namaSekolah || 'Sekolah Saya', label: `${item.mapel} · Kelas ${item.kelas} ${item.jenjang || ''}` }] })).values()])
const loadRooms = async () => { if (!user.value) return; const snap = await getDocs(query(collection(db, 'ruangKolaborasi'), where('memberIds', 'array-contains', user.value.uid), limit(30))); rooms.value = snap.docs.map(item => ({ id: item.id, ...item.data() })) }
const createRoom = async () => { const created = await addDoc(collection(db, 'ruangKolaborasi'), { ownerId: user.value.uid, userId: user.value.uid, nama: form.nama, izin: 'lihat', memberIds: [user.value.uid], editorIds: [user.value.uid], questionIds: [], questions: [], createdAt: new Date(), updatedAt: new Date() }); await catatAktivitas('ruang_kolaborasi_dibuat', { ruangId: created.id }); form.nama = ''; await loadRooms(); success('Ruang dibuat. Tambahkan soal lalu bagikan kodenya.') }
const joinRoom = async () => { try { const target = await getDoc(doc(db, 'ruangKolaborasi', joinCode.value)); if (!target.exists()) throw new Error('Kode ruang tidak ditemukan'); await updateDoc(target.ref, { memberIds: arrayUnion(user.value.uid), updatedAt: new Date() }); joinCode.value = ''; await loadRooms(); success('Berhasil bergabung.') } catch (e) { error(e.message || 'Tidak dapat bergabung. Minta pemilik menambahkan UID Anda.') } }
const copyCode = async code => { await navigator.clipboard.writeText(code); success('Kode ruang disalin.') }
const addQuestions = async () => { const room = rooms.value.find(item => item.id === selectedRoomId.value); if (!room) return; const existing = room.questions || []; const additions = ownQuestions.value.filter(item => selectedQuestionIds.value.includes(item.id)).map(({ id, userId, ...item }) => ({ sourceId: id, sourceOwnerId: user.value.uid, ...item })); const merged = [...existing, ...additions.filter(item => !existing.some(saved => saved.sourceId === item.sourceId))].slice(0, 200); await updateDoc(doc(db, 'ruangKolaborasi', room.id), { questions: merged, questionIds: merged.map(item => item.sourceId), updatedAt: new Date() }); selectedQuestionIds.value = []; selectedRoomId.value = ''; await loadRooms(); success('Soal ditambahkan ke ruang bersama.') }
const copyRoomQuestions = async room => { const destination = destinationOptions.value.find(item => item.key === destinationKey.value); if (!destination) return; copyingRoomId.value = room.id; try { const context = { teacherId: user.value.uid, assignmentId: destination.assignmentId, classLevel: destination.kelas, subject: destination.mapel, schoolName: destination.namaSekolah, educationLevel: destination.jenjang }; await ensureBank(context); let copied = 0; const existing = new Set(ownQuestions.value.map(item => String(item.pertanyaan || '').trim().toLowerCase())); for (const shared of room.questions || []) { const fingerprint = String(shared.pertanyaan || '').trim().toLowerCase(); if (!fingerprint || existing.has(fingerprint)) continue; const { sourceId, sourceOwnerId, createdAt, updatedAt, assignmentId, kelas, mapel, jenjang, namaSekolah, bankId, ...content } = shared; const saved = await addDoc(questionsRefFor(context), { ...content, userId: user.value.uid, createdBy: user.value.uid, bankId: bankIdFor(context), assignmentId: destination.assignmentId, kelas: Number(destination.kelas), mapel: destination.mapel, jenjang: destination.jenjang, namaSekolah: destination.namaSekolah, status: 'aktif', dipakai: false, jumlahDicetak: 0, sourceRoomId: room.id, createdAt: new Date(), updatedAt: new Date() }); ownQuestions.value.push({ id: saved.id, bankId: bankIdFor(context), ...content, ...destination, userId: user.value.uid, createdBy: user.value.uid, status: 'aktif' }); existing.add(fingerprint); copied++ } await catatAktivitas('soal_ruang_disalin', { ruangId: room.id, jumlah: copied }); success(`${copied} soal baru disalin ke ${destination.mapel} Kelas ${destination.kelas}.`) } catch (e) { error(`Soal gagal disalin: ${e.message}`) } finally { copyingRoomId.value = '' } }
const deleteRoom = async room => { if (!confirm(`Hapus ruang “${room.nama}”?`)) return; await deleteDoc(doc(db, 'ruangKolaborasi', room.id)); await loadRooms() }
onMounted(async () => { await loadRooms(); if (!user.value) return; const snap = await getDocs(query(collectionGroup(db, 'questions'), where('createdBy', '==', user.value.uid), where('status', '==', 'aktif'), limit(100))); ownQuestions.value = snap.docs.map(item => ({ id: item.id, ...item.data() })) })
</script>
